version: '3'
services:
  p2p-editor:
    build: .
    ports:
      - "3617:3617"
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    depends_on:
      - signalhub
  signalhub:
    build:
      context: .
      dockerfile: ./signalhub.Dockerfile
    ports:
      - "3618:3618"
