version: '3'
services:
  p2p-editor:
    build: .
    ports:
      - "3617:3617"
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
  signalhub:
    image: "santaka/signalhub"
    ports:
      - "3618:8080"
