version: '3'
services:
  p2p-editor:
    build:
      context: .
      dockerfile: "p2p-editor.Dockerfile"
    ports:
      - "8000:80"
  signalhub:
    build:
      context: .
      dockerfile: "signalhub.Dockerfile"
    ports:
      - "8080:8080"
